services:
  windows:
    container_name: windows
    build:
      context: .
      dockerfile: Dockerfile.codespace
    environment:
      RAM_SIZE: "8G"
      DISK_SIZE: "64G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 2222:22
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./shared:/shared
      - ./oem:/oem
    restart: on-failure
    stop_grace_period: 2m
