FROM ghcr.io/dockur/windows:latest

RUN apt-get update && apt-get install -y openssh-server sshpass && \
    mkdir -p /run/sshd && \
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
    echo 'PermitEmptyPasswords yes' >> /etc/ssh/sshd_config && \
    passwd -d root && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN printf '#!/bin/bash\n/usr/sbin/sshd\nexec /usr/bin/tini -s /run/entry.sh\n' > /start.sh && chmod +x /start.sh

ENTRYPOINT ["/start.sh"]
